source("Rscripts/utils.R")

if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("BSgenome")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
install.packages("deconstructSigs")
install.packages("getopt")
install.packages("mutSignatures")
install.packages("tidyverse")
