"""
MAFigate Test Suite
==================

Comprehensive test suite for the MAFigate application covering:
- Utility functions (MAF file reading, data processing)
- Filtering logic (somatic and germline filters)
- UI components (parameter validation, session state)
- Configuration management
- Integration tests

Test Structure:
- test_utils.py: Tests for utility functions, including the MAF loader
- test_filter_entry_point.py: The filter entry point, asserted against the pipeline
  verdicts recorded in fixtures/parity/MANIFEST.json — needs no `bin/`
- test_components.py: Tests for UI components
- test_config.py: Tests for configuration management
- test_param_contract.py: config/pipeline_params.py against nextflow.config
- test_vendor_drift.py, test_vendor_compute_keep.py: vendor/ against bin/
- parity/: the harness comparing the app to bin/filter_variants.py; skipped without `bin/`
- fixtures/: Test data and mock files

The governing rule for where a test belongs: **the parity harness owns every behaviour
with a pipeline counterpart, the unit suite owns every behaviour without one.**
`test_filter_entry_point.py` is the third instrument — it asserts pipeline-matching
behaviour without needing the pipeline, by comparing against verdicts already frozen in
git, which is what keeps the filter path asserted in a packaged build.

**`README.md` in this directory is the full account** — every module against that rule in
one table, the house pattern the app's copies of pipeline lists are held to, and the two
failure modes the suite is designed against. The table is not decoration:
`test_suite_organisation.py` asserts that every module has a row, that no row names a
module that is gone, and that nothing filed as `net` or `unit` has quietly acquired a
dependency on `bin/`.

`test_filters.py` and `test_integration.py` were deleted by issue #33: they were built
around three app-side filter functions that no longer exist, the app's filter decision
now being made by the vendored pipeline code.
"""

import os
import sys
import pytest
import pandas as pd
import io

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Test constants
TEST_DATA_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
SAMPLE_MAF_CONTENT = """# MAF version 2.4
# Generated by MAFigate Test Suite
Hugo_Symbol	Entrez_Gene_Id	Center	NCBI_Build	Chromosome	Start_Position	End_Position	Strand	Variant_Classification	Variant_Type	Reference_Allele	Tumor_Seq_Allele1	Tumor_Seq_Allele2	Tumor_Sample_Barcode	Matched_Norm_Sample_Barcode	Match_Norm_Seq_Allele1	Match_Norm_Seq_Allele2	Tumor_Validation_Allele1	Tumor_Validation_Allele2	Match_Norm_Validation_Allele1	Match_Norm_Validation_Allele2	Verification_Status	Validation_Status	Mutation_Status	Sequencing_Phase	Sequence_Source	Validation_Method	Score	BAM_File	Sequencer	DP	tumor_f	normal_f	gnomAD_exome_AF	gnomAD_genome_AF	CancerVar	InterVar	ClinVar_VCF_CLNSIG	ESCAT	CIViC_Evidence_Level
BRCA1	672	TestCenter	GRCh38	17	43044295	43044295	+	Missense_Mutation	SNP	G	G	A	TCGA-TEST-01	TCGA-TEST-10	G	G	G	A	G	G	Unknown	Unknown	Somatic	Phase_I	Capture	none	.	test.bam	Illumina HiSeq	45	0.25	0.02	0.001	0.0008	1#Tier_I_strong Evidence	Pathogenic	Pathogenic	I	A
TP53	7157	TestCenter	GRCh38	17	7673803	7673803	+	Nonsense_Mutation	SNP	C	C	T	TCGA-TEST-01	TCGA-TEST-10	C	C	C	T	C	C	Unknown	Unknown	Somatic	Phase_I	Capture	none	.	test.bam	Illumina HiSeq	52	0.38	0.01	0.0001	0.0002	1#Tier_I_strong Evidence	Pathogenic	Pathogenic	I	A
EGFR	1956	TestCenter	GRCh38	7	55181378	55181378	+	Missense_Mutation	SNP	C	C	G	TCGA-TEST-01	TCGA-TEST-10	C	C	C	G	C	C	Unknown	Unknown	Somatic	Phase_I	Capture	none	.	test.bam	Illumina HiSeq	30	0.15	0.03	0.05	0.04	1#Tier_II_potential Evidence	Likely pathogenic	Likely_pathogenic	II	B
KRAS	3845	TestCenter	GRCh38	12	25245351	25245351	+	Silent	SNP	G	G	A	TCGA-TEST-01	TCGA-TEST-10	G	G	G	A	G	G	Unknown	Unknown	Somatic	Phase_I	Capture	none	.	test.bam	Illumina HiSeq	25	0.08	0.05	0.15	0.12	1#Tier_III_unknown Evidence	Uncertain_significance	Uncertain_significance	III	C
PIK3CA	5290	TestCenter	GRCh38	3	179234297	179234297	+	Frame_Shift_Del	DEL	AG	AG	-	TCGA-TEST-01	TCGA-TEST-10	AG	AG	AG	-	AG	AG	Unknown	Unknown	Somatic	Phase_I	Capture	none	.	test.bam	Illumina HiSeq	5	0.02	0.01	.	.	.	.	.	.	.
"""


def create_test_maf_file() -> io.StringIO:
    """Create a test MAF file for testing purposes."""
    return io.StringIO(SAMPLE_MAF_CONTENT)


def create_test_dataframe() -> pd.DataFrame:
    """Create a test DataFrame from sample MAF content."""
    from utils import read_maf

    return read_maf(create_test_maf_file())
